# Generated by Django 4.0.6 on 2022-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='battle_cry',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='death_rattle',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='discription',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='sorcery',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
