# Generated by Django 4.0.6 on 2022-08-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0002_alter_card_archetype_alter_card_battle_cry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tavern_level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
