# Generated by Django 4.0.6 on 2022-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0003_card_tavern_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='discription',
            new_name='card_about',
        ),
    ]
