# Generated by Django 4.0.6 on 2022-08-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0005_alter_card_archetype_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='battle_cry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_about',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='death_rattle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sorcery',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
