# Generated by Django 4.0.6 on 2022-08-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0008_alter_card_archetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'verbose_name': '123', 'verbose_name_plural': '321'},
        ),
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hs.archetype', verbose_name='Archetype'),
        ),
    ]
