# Generated by Django 4.0.6 on 2022-08-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0009_alter_archetype_options_alter_card_archetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'verbose_name': 'название архитипа', 'verbose_name_plural': 'название архетипов'},
        ),
    ]
