# Generated by Django 4.0.6 on 2022-08-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0010_alter_archetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'verbose_name': 'название архетипа', 'verbose_name_plural': 'название архетипов'},
        ),
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.ForeignKey(db_column='Archetype.name', on_delete=django.db.models.deletion.CASCADE, to='hs.archetype', verbose_name='Archetype'),
        ),
    ]
