# Generated by Django 4.0.6 on 2022-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0012_alter_archetype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ид'),
        ),
    ]
