# Generated by Django 4.0.6 on 2022-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0013_alter_archetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
