# Generated by Django 4.0.6 on 2022-08-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0014_alter_archetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='battle_cry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='death_rattle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sorcery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
