# Generated by Django 4.0.6 on 2022-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0015_alter_card_battle_cry_alter_card_death_rattle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_about',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
