# Generated by Django 4.0.6 on 2022-08-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0017_alter_card_battle_cry_alter_card_death_rattle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hs.archetype', verbose_name='Archetype'),
        ),
    ]
