# Generated by Django 4.0.6 on 2022-08-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0018_alter_card_archetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('feature_disc', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='battle_cry',
        ),
        migrations.RemoveField(
            model_name='card',
            name='death_rattle',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sorcery',
        ),
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hs.archetype', verbose_name='Archetype'),
        ),
    ]
