# Generated by Django 4.0.6 on 2022-08-04 08:39

from django.db import migrations, models
import django.db.models.deletion
import hs.models


class Migration(migrations.Migration):

    dependencies = [
        ('hs', '0022_card_has_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardfeature',
            options={'verbose_name': 'способности карт', 'verbose_name_plural': 'Способности карт'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'название способности', 'verbose_name_plural': 'Способности'},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_about',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FilePathField(blank=True, path=hs.models.images_path, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='cardfeature',
            name='card',
            field=models.ForeignKey(default='', limit_choices_to={'has_features': 1}, on_delete=django.db.models.deletion.CASCADE, to='hs.card', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Способность'),
        ),
    ]
